//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Meow.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MeowParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IMeowListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MeowParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MeowParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] MeowParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] MeowParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] MeowParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] MeowParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] MeowParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] MeowParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] MeowParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] MeowParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] MeowParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] MeowParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfExpression([NotNull] MeowParser.IfExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.ifExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfExpression([NotNull] MeowParser.IfExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] MeowParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] MeowParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MeowParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] MeowParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MeowParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] MeowParser.LiteralContext context);
}
